// alu_top.v
// Convenience wrapper: connects alu_control + alu_core and provides simple operand muxing.
// Inputs typically come from decoder/ID stage and regfile.
// - rs1_data, rs2_data: data read from regfile
// - imm: immediate generated by ID
// - alu_src: if 1 use imm as second operand; else use rs2_data
// - alu_op/funct3/funct7: control inputs from decoder/id_stage
// Outputs:
// - alu_result: 32-bit ALU result
// - zero, slt, sltu: flags for branch unit and other uses
`timescale 1ns/1ps
module alu_top (
    input  wire [2:0]  alu_op,
    input  wire [2:0]  funct3,
    input  wire [6:0]  funct7,
    input  wire [31:0] rs1_data,
    input  wire [31:0] rs2_data,
    input  wire [31:0] imm,
    input  wire        alu_src,     // 1 -> imm, 0 -> rs2
    output wire [31:0] alu_result,
    output wire        zero,
    output wire        slt,
    output wire        sltu
);

    wire [3:0] alu_ctrl;
    wire [31:0] op2;
    // For LUI we expect imm already shifted left 12 by ID (imm for U-type), but in our ID we did imm = {inst[31:12],12'b0}
    // We keep convention: when ALU_CTRL==A_LUI, op2 should be imm (already shifted), op1 is ignored.

    assign op2 = alu_src ? imm : rs2_data;

    // ALU control stage
    alu_control u_alu_control (
        .alu_op(alu_op),
        .funct3(funct3),
        .funct7(funct7),
        .alu_ctrl(alu_ctrl)
    );

    // ALU core
    alu_core u_alu_core (
        .op1(rs1_data),
        .op2(op2),
        .alu_ctrl(alu_ctrl),
        .result(alu_result),
        .zero(zero),
        .slt(slt),
        .sltu(sltu)
    );

endmodule
